create table course
(
    id number generated by default as identity
        not null,

    code varchar2(50 byte)
        not null,

    title varchar2(200 byte)
        not null,

    description clob,

    category_code varchar2(50 byte),

    level_code varchar2(30 byte),

    duration_hours number(6,2),

    status_code varchar2(30 byte)
        default 'ACTIVE'
        not null,

    created_at timestamp(6)
        default systimestamp
        not null,

    updated_at timestamp(6),

    constraint pk_course
        primary key (id),

    constraint uk_course_code
        unique (code),

    constraint ck_course_duration
        check (
            duration_hours is null
            or duration_hours > 0
        ),

    constraint ck_course_level
        check (
            level_code is null
            or level_code in (
                'BEGINNER',
                'INTERMEDIATE',
                'ADVANCED'
            )
        ),

    constraint ck_course_status
        check (
            status_code in (
                'ACTIVE',
                'INACTIVE'
            )
        )
);