
  CREATE TABLE "SESSION_TRAINER"
   (	"SESSION_ID" NUMBER NOT NULL ENABLE,
	"TRAINER_ID" NUMBER NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(30 BYTE) DEFAULT 'TRAINER' NOT NULL ENABLE
   ) ;
ALTER TABLE "SESSION_TRAINER" ADD CONSTRAINT "CK_ST_ROLE" CHECK (
            role_code IN (
                'LEAD',
                'TRAINER',
                'ASSISTANT',
                'GUEST'
            )
        ) ENABLE;
ALTER TABLE "SESSION_TRAINER" ADD CONSTRAINT "PK_SESSION_TRAINER" PRIMARY KEY ("SESSION_ID", "TRAINER_ID")
  USING INDEX  ENABLE;
ALTER TABLE "SESSION_TRAINER" ADD CONSTRAINT "FK_ST_SESSION" FOREIGN KEY ("SESSION_ID")
	  REFERENCES "TRAINING_SESSION" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "SESSION_TRAINER" ADD CONSTRAINT "FK_ST_TRAINER" FOREIGN KEY ("TRAINER_ID")
	  REFERENCES "TRAINER" ("ID") ENABLE;

