
-- Generated by ORDS REST Data Services 26.1.1.r1321130
-- Schema: ORACLE_ACADEMY
--

DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'Oracle Academy API v1',
      p_base_path      => '/api/v1/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Oracle Academy API v1',
      p_pattern        => 'sessions/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Collection des Training Sessions');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Oracle Academy API v1',
      p_pattern        => 'sessions/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'select
    id,
    session_code        as code,
    course_id,
    course_code,
    course_title,
    category_code       as category,
    level_code,
    to_char(start_date, ''YYYY-MM-DD'') as start_date,
    to_char(end_date,   ''YYYY-MM-DD'') as end_date,
    capacity,
    location,
    status_code         as status,
    enrollment_count,
    available_seats,
    trainer_count,
    meeting_count
from vw_session_overview
where (:status is null or status_code = upper(:status))
order by start_date desc, session_code');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Oracle Academy API v1',
      p_pattern        => 'sessions/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get Session By Id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'Oracle Academy API v1',
      p_pattern        => 'sessions/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'select
    id,
    session_code        as code,
    course_id,
    course_code,
    course_title,
    category_code       as category,
    level_code,
    to_char(start_date, ''YYYY-MM-DD'') as start_date,
    to_char(end_date,   ''YYYY-MM-DD'') as end_date,
    capacity,
    location,
    status_code         as status,
    enrollment_count,
    available_seats,
    trainer_count,
    meeting_count
from vw_session_overview
where id = :id');

  ORDS.CREATE_ROLE(
      p_role_name=> 'academy.api.reader');
  l_roles(1) := 'academy.api.reader';
  l_modules(1) := 'Oracle Academy API v1';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'academy.sessions.read',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'Academy Sessions Read',
      p_description    => 'Read access to Oracle Academy training sessions REST API.',
      p_comments       => 'Grants read access to the Sessions API v1.');

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;
